%% Internal Transfer Process Flow
swimlane-beta TB

  subgraph S&OP
    start([เริ่มต้น])
    a1[ขอย้าย FG]
    a2[ตรวจสอบจำนวนคงคลัง]
    a3{FG เพียงพอโอนย้ายหรือไม่}
    a4[สร้างรายการโอนย้าย]
    a5[ทำการโอนย้าย]
    a6[ใบโอนย้ายสินค้าระหว่างคลัง]
    done([สิ้นสุด])
  end

  %% Success Flows
  start e1@--> a1
  a1 e2@--> a2
  a2 e3@--> a3
  a3 e4@--> a4
  a4 e5@--> a5
  a5 e6@--> a6
  a6 e7@--> done

  classDef attention fill:#fff2cc;
  class start attention;
  class done attention;
  class a1 attention;
  class a2 attention;
  class a3 attention;
  class a4 attention;
  class a5 attention;
  class a6 attention;

  e1@{ animate: true}
  e2@{ animate: true}
  e3@{ animate: true}
  e4@{ animate: true}
  e5@{ animate: true}
  e6@{ animate: true}
  e7@{ animate: true}